projects_homepage:
    path:     /projects
    defaults: { _controller: ProjectsBundle:Projects:index }

projects_add:
    path:     /projects/add
    defaults: { _controller: ProjectsBundle:Projects:add }
