parameters:
#    projects.example.class: Imie\ProjectsBundle\Example

services:
#    projects.example:
#        class: %projects.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
