users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /

roles:
    resource: "@RolesBundle/Resources/config/routing.yml"
    prefix:   /

projects:
    resource: "@ProjectsBundle/Resources/config/routing.yml"
    prefix:   /

home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

workgroups:
    resource: "@WorkgroupsBundle/Resources/config/routing.yml"
    prefix:   /

imieskills:
    resource: "@ImieskillsBundle/Resources/config/routing.yml"
    prefix:   /

