security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Imie\UsersBundle\Entity\Users: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        main :
            entity: { class: Imie\UsersBundle\Entity\Users, property: login }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /login

        # secured_area:
            # pattern:    ^/
            # anonymous: ~
            # form_login:
                # login_path:  /login
                # check_path:  /login_check
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        # - { path: ^/login, roles: IS_AUTHENTICATED_FULLY, requires_channel: http }
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /.*, role: IS_AUTHENTICATED_FULLY }
