parameters:
#    workgroups.example.class: Imie\WorkgroupsBundle\Example

services:
#    workgroups.example:
#        class: %workgroups.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
