imieskills_skills_list:
    path:     /skills
    defaults: { _controller: ImieskillsBundle:Skills:index }

imieskills_skills_add:
    path:     /skills/add
    defaults: { _controller: ImieskillsBundle:Skills:add }
