imieskills_skills:
    path:     /skills/{name}
    defaults: { _controller: ImieskillsBundle:Skills:index }

imieskills_skills_list:
    path:     /skills
    defaults: { _controller: ImieskillsBundle:Skills:index }
