imieskills_skills:
    path:     /skill
    defaults: { _controller: ImieskillsBundle:Skills:getAllSkills }

imieskills_skills_list:
    path:     /skills
    defaults: { _controller: ImieskillsBundle:Skills:index }
