<?php

namespace Imie\WorkgroupsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkgroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkgroupsRepository extends EntityRepository
{
}
