<?php

namespace Imie\ProjectsBundle\Entity;

use Doctrine\ORM\EntityRepository;


/**
 * skillsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectsRepository extends EntityRepository
{
	public function findAll() {
		return $this->createQueryBuilder('p')
		//>add('select', 'libelle')
		//->add('from', 'skills as s')
		->getQuery()
		->getResult();
	}

	/*public function find($id) {
		return $this->createQueryBuilder('s')
		->
		->
	}*/
}
